---
title: "Week 1 Practice Exercises"
output: html_document
---

### Exercise 1.1
#### A migraine is a particularly painful type of headache, which patients sometimes wish to treat with acupunctrure. To determine whether acupunctrure relieves migrain pain, researchers conducted a randomized controlled study where 89 females diagnosed with migraine headaches were randomly assigned to one of two groups: treatment or control. 43 patients in the treatment group received acupuncture that is specifically designd to treat migraines. 46 patients in the control group received placebo acupuncture (needle insertion at non-acupoint locations). 24 hours after patients received acupunctrue, they were asked if they were pain free. Results are summarized in the contingency table below.

Group    |Pain free |No  |Total
---------|----------|----|-----
Treatment|10        |33  |43
Control  |2         |44  |46
Total    |12        |77  |89

#### What percent of patients in the treatment group were pain free 24 hours after receiving acupuncture? What percentage in the control group?
```{r echo=FALSE}
t_success <- 10/43*100
c_success <- 2/46*100

paste("Succes rate was ",t_success,"% in the treatment group, and ", c_success, "% in the control group.", sep="")
```
#### At first glance, does acupuncture appear to be an effective treatment for migraines? Explain your reasoning.
There is roughly a 19% difference between the control and treatment groups, which at first glance suggests that the treatment group is more likely to have pain reduction.
#### Do the data provide convincing evidence that there is a real pain reduction for those patients in the treatment group Or do you think that the observed difference might just be due to chance?
There is a fairly sizable difference in effectiveness between the two groups, which seems to suggest that there is real pain reduction for those who receive acupuncture treatment.

###Exercise 1.3
#### Researchers collected data to examine the relationship between air pollutants and preterm births in Southern California. During the study air pollution levels were measured by air quality monitoring stations. Specifically, levels of carbon monoxide were recorded in parts per million, nitrogen dioxide and ozone in parts per hundred million, and coarse particulate matter (PM_10) in \mu g/m^3^. Length of gestation data were collected on 143,196 births between the years 1989 and 1993, and air pollution exposure during gestation was calculated for each birth. The analys suggested that increased ambient PM_10 and to a lesser degree, CO concentrations may be associated with the occurence of preterm births.
#### Identify:
#### (a) the cases,
143,169 births between the years of 1989 and 1993

#### (b) the variables and their types, and
* level of carbon monoxide, continuous numerical
* levels of nitrogen dioxide, continuous numerical
* levels of ozone, continuous numerical
* levels of particulate matter, continuous numerical
* length of gestation, continuous numerical

#### (c) the main research question.
Is there a correlation between air polution and preterm births?

### Exercise 1.11
#### As part of this study, 600 asthma patients aged 18-69 who relied on medication for asthma treatment were recruited and randomly assigned to two groups: one practiced the Buteyko method and the other did not. Those in the Buteyko group experienced, on average, a significat reduction in asthma symptoms and an improvement in quality of life.
#### Identify the population of interest and the sample in this study.
The population of interest is all asthma patients aged 18-69 who rely on medication for asthma treatment. The sample in this study is the 600 patients.
#### Comment on whether or not the study can be generalized to the population, and if the findings of the study can be used to establish causal relationships.
Since the study is experimental, it can be used to establish causal relationships, but can only be generalized to the population if the sample is representative of the population.

###Exercise 1.13
#### The 2010 General Social Survey asked the question, "After an average work day, about how many hours do you have to relax or pursue activities that you enjoy?" to a random sample of 1,155 Americans. The average relaxing time was found to be 1.65 hours. Determine 

###Exercise 1.17
####

###Exercise 1.19
####

###Exercise 1.25
####

###Exercise 1.27
####

###Exercise 1.31
####

